$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$sourceRoot = Join-Path $repositoryRoot "src"
$distributionRoot = Join-Path $repositoryRoot "dist"
$outputPath = Join-Path $distributionRoot "AstraUI.lua"
$legacyOutputPath = Join-Path $distributionRoot "ModernUI.lua"

if (-not (Test-Path -LiteralPath $sourceRoot)) {
	throw "Source directory was not found: $sourceRoot"
}

$modules = [ordered]@{}
$sourceFiles = Get-ChildItem -LiteralPath $sourceRoot -Recurse -File -Filter "*.lua" |
	Sort-Object FullName

foreach ($file in $sourceFiles) {
	$relativePath = $file.FullName.Substring($sourceRoot.Length + 1)
	$moduleName = $relativePath.Substring(0, $relativePath.Length - 4).Replace("\", ".")
	$modules[$moduleName] = [System.IO.File]::ReadAllText($file.FullName)
}

if (-not $modules.Contains("Library")) {
	throw "The entry module src/Library.lua is missing."
}

$missingDependencies = New-Object System.Collections.Generic.List[string]
foreach ($entry in $modules.GetEnumerator()) {
	$matches = [regex]::Matches($entry.Value, 'Require\("([^"]+)"\)')
	foreach ($match in $matches) {
		$dependency = $match.Groups[1].Value
		if (-not $modules.Contains($dependency)) {
			$missingDependencies.Add("$($entry.Key) requires missing module $dependency")
		}
	}
}

if ($missingDependencies.Count -gt 0) {
	throw ($missingDependencies -join [Environment]::NewLine)
}

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Astra UI v1.1.0")
[void]$builder.AppendLine("-- Generated by scripts/build.ps1. Edit files in src/ instead.")
[void]$builder.AppendLine("local moduleSources = {")

foreach ($entry in $modules.GetEnumerator()) {
	$equals = ""
	while ($entry.Value.Contains("]$equals]")) {
		$equals += "="
	}
	$open = "[$equals["
	$close = "]$equals]"
	[void]$builder.AppendLine("`t[`"$($entry.Key)`"] = $open")
	[void]$builder.Append($entry.Value)
	if (-not $entry.Value.EndsWith("`n")) {
		[void]$builder.AppendLine()
	}
	[void]$builder.AppendLine("$close,")
}

[void]$builder.AppendLine("}")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("local cache = {}")
[void]$builder.AppendLine("local loading = {}")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("local function Require(name)")
[void]$builder.AppendLine("`tif cache[name] ~= nil then")
[void]$builder.AppendLine("`t`treturn cache[name]")
[void]$builder.AppendLine("`tend")
[void]$builder.AppendLine("`tassert(not loading[name], `"Circular module dependency: `" .. tostring(name))")
[void]$builder.AppendLine("`tlocal source = moduleSources[name]")
[void]$builder.AppendLine("`tassert(source, `"Unknown Astra UI module: `" .. tostring(name))")
[void]$builder.AppendLine("`tloading[name] = true")
[void]$builder.AppendLine("`tlocal chunk, compileError = loadstring(source, `"@AstraUI/`" .. name)")
[void]$builder.AppendLine("`tassert(chunk, compileError)")
[void]$builder.AppendLine("`tlocal ok, factory = xpcall(chunk, debug.traceback)")
[void]$builder.AppendLine("`tassert(ok, factory)")
[void]$builder.AppendLine("`tlocal result = type(factory) == `"function`" and factory(Require) or factory")
[void]$builder.AppendLine("`tcache[name] = result")
[void]$builder.AppendLine("`tloading[name] = nil")
[void]$builder.AppendLine("`treturn result")
[void]$builder.AppendLine("end")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("local LibraryClass = Require(`"Library`")")
[void]$builder.AppendLine("local defaultInstance")
[void]$builder.AppendLine("local export = { Version = LibraryClass.Version }")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("function export.new(first, second)")
[void]$builder.AppendLine("`tlocal options = first == export and second or first")
[void]$builder.AppendLine("`treturn LibraryClass.new(options)")
[void]$builder.AppendLine("end")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("setmetatable(export, {")
[void]$builder.AppendLine("`t__index = function(_, key)")
[void]$builder.AppendLine("`t`tdefaultInstance = defaultInstance or LibraryClass.new()")
[void]$builder.AppendLine("`t`tlocal value = defaultInstance[key]")
[void]$builder.AppendLine("`t`tif type(value) == `"function`" then")
[void]$builder.AppendLine("`t`t`treturn function(first, ...)")
[void]$builder.AppendLine("`t`t`t`tif first == export then")
[void]$builder.AppendLine("`t`t`t`t`treturn value(defaultInstance, ...)")
[void]$builder.AppendLine("`t`t`t`tend")
[void]$builder.AppendLine("`t`t`t`treturn value(defaultInstance, first, ...)")
[void]$builder.AppendLine("`t`t`tend")
[void]$builder.AppendLine("`t`tend")
[void]$builder.AppendLine("`t`treturn value")
[void]$builder.AppendLine("`tend,")
[void]$builder.AppendLine("})")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("return export")

[System.IO.Directory]::CreateDirectory($distributionRoot) | Out-Null
$encoding = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString(), $encoding)
[System.IO.File]::WriteAllText($legacyOutputPath, $builder.ToString(), $encoding)

Write-Output "Built $($modules.Count) modules into $outputPath"
Write-Output "Updated compatibility bundle at $legacyOutputPath"
